# Generated by Django 3.2 on 2021-04-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_note_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
