# Generated by Django 3.2 on 2021-04-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210415_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='nds',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
