# Generated by Django 3.2 on 2021-04-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_note_nds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
