# Generated by Django 3.2 on 2021-04-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_note_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='nds',
            field=models.FloatField(null=True),
        ),
    ]
