# Generated by Django 3.2 on 2021-04-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_note_nds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='nds',
        ),
    ]
